export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="bira"

HYPHEN_INSENSITIVE="true"

zstyle ':omz:update' mode reminder  # just remind me to update when it's time

zstyle ':omz:update' frequency 7

COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"

HIST_STAMPS="dd-mm-yyyy"

#plugins=(git)

source $ZSH/oh-my-zsh.sh

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#setopt PROMPT_SUBST
#PROMPT='%T %2~  %n ${git rev-parse --abbrev-ref HEAD}'
# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

# Generated by Webi. Do not edit.
eval "$(webi --init zsh)"

# added by Webi for pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export PATH=$PATH:$HOME/dotfiles
